import Head from 'next/head';
import styles from '../styles/Home.module.css';
import NavBar from './NavBar';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Giphy App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar className={styles.container} />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="./Emily">My app!</a>
        </h1>

        <p className={styles.description}>
          Learn more about me by{' '}
          <a className={styles.code} href="./Emily">
            clicking here.
          </a>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          By Emily Nadler{' '}
        </a>
      </footer>
    </div>
  );
}
